inputDir: '../../data/'
outputDir: '../../osemosys_global_model/'
modelName: 'OsemosysGlobal'
region: 'GLOBAL'
startYear: 2015
endYear: 2050
daytype: False
scenario: 'OsemosysGlobal'
geographic_scope:
  - 'IND'
  - 'AFG'
crossborderTrade: False
