# High Level Configuration
inputDir: '../../data/'
outputDir: '../../osemosys_global_model/'
modelName: 'OsemosysGlobal'
region: 'GLOBAL'

# Unique Scenario Name 
scenario: 'OsemosysGlobal'

# Temporal Parameters 
startYear: 2015
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour, end_hour]
  D1: [0, 12]
  D2: [12, 24]
seasons:
  #season : [month_1, month_2, ...]
  S1: [12, 1, 2]
  S2: [3, 4, 5]
  S3: [6, 7, 8]
  S4: [9, 10, 11]
  
# Spatial Parameters 
geographic_scope:
  - 'IND'
  - 'AFG'
