# High Level Configuration
inputDir: 'resources'
outputDir: 'results'
modelName: 'OsemosysGlobal'
region: 'GLOBAL'

# Scenario Name 
scenario: 'osemosys-global'

# Temporal Parameters 
startYear: 2015
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [0, 12]
  D2: [12, 24]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [6, 7, 8, 9, 10, 11, 12]
  # S3: [6, 7, 8]
  # S4: [9, 10, 11]
  
# Spatial Parameters 
geographic_scope:
  - 'IND'
  - 'NPL'
  - 'BGD'
  - 'BTN'
crossborderTrade: True

# Emission Parameters 
emission_penalty: 50 # M$/MT CO2

# Investment Parameters 
no_invest_technologies: 
  - 'GEO'
  - 'CSP'
  - 'WAV'
  - 'BIO'

# Result Parameters 
results_by_country: True

user_defined_capacity:
  #technology: [capacity, first_year,]
  TRNINDEANPLXX: [10, 2017]
  TRNINDEAINDSO: [5, 2048]
  TRNINDNOINDWE: [2, 2035]
