# Scenario Name 
scenario: "India"

# Temporal Parameters 
startYear: 2021
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [1, 7]
  D2: [7, 13]
  D3: [13, 19]
  D4: [19, 25]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]

timeshift: 0 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
  - "IND"

crossborderTrade: True

# Emission Parameters 
emission_penalty: 
# - [EMISSION, COUNTRY, START_YEAR, END_YEAR, VALUE]
# where VALUE is in M$/MT CO2
 - ["CO2", "IND", 2020, 2050, 2.1]

# Investment Parameters 
no_invest_technologies: 
  - "CSP"
  - "WAV"
  - "URN"
  - "OTH"
  - "WAS"
  - "COG" 
  - "GEO"
  - "BIO"
  - "PET"

# Result Parameters 
results_by_country: True

# solver parameters
solver: "cbc" # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, 
  #              build_year, 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              capex_cost, 
  #              efficiency]
  PWRCOAINDWE01: [8, 2000, 2025, 5, 1100, 35]
  PWRBIOINDWE01: [0, 2020, 2030, 2, 2000, 28]

user_defined_capacity_transmission:
  # entry: [technology,
  #         capacity, 
  #         build_year, 
  #         first_year_of_expansion, 
  #         build_rate_per_year, 
  #         capex_cost,
  #         annual_fixed_O&M_cost,
  #         efficiency]
  trn1: [TRNINDEAINDNE, 5, 1975, 2030, 10, 861, 30, 95]
  trn2: [TRNINDEAINDNE, 1, 1990, 2030, 10, 861, 30, 95]
  trn3: [TRNINDEAINDNE, 2, 2035, 2030, 10, 861, 30, 95]
  trn4: [TRNINDNOINDSO, 0, 2020, 2025, 0.5, 900, 32, 92]
  # Per technology, only the capacity and build_year
  # parameters can deviate from each other. For all other
  # parameters only the last entry will be used.

user_defined_capacity_storage:
  # entry: [technology, 
  #              capacity, 
  #              build_year, 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              capex_cost, 
  #              roundtrip_efficiency]
  sto1: [PWRSDSINDEA01, 0, 2020, 2025, 3, 450, 87]
  sto2: [PWRLDSINDNE01, 4, 1980, 2025, 2, 350, 82]
  sto3: [PWRLDSINDNE01 ,1, 2030, 2025, 2, 350, 82]
  # Per technology, only the capacity and build_year
  # parameters can deviate from each other. For all other
  # parameters only the last entry will be used.

transmission_parameters:
  # technology_group: [Line CAPEX, 
  #                    Converter pair CAPEX, 
  #                    Line losses, 
  #                    AC/DC Converter pair losses, 
  #                    Fixed O&M costs]
  # Units are in $2020/MW/KM (Line CAPEX), $2020 (Converter pair CAPEX),
  # %/1000km (Line losses), % (AC/DC Converter pair losses), 
  # % of total CAPEX/yr (Fixed O&M costs).
  HVAC: [779, 95400, 6.75, 0, 3.5]
  HVDC: [238, 297509, 3.5, 1.3, 3.5]
  HVDC_subsea: [295, 297509, 3.5, 1.3, 3.5]

storage_parameters:
  # technology_group: [CAPEX, 
  #                    roundtrip_efficiency]
  # Units are in $2020/MW/KM (Line CAPEX)
  SDS: [484.5, 85]
  LDS: [379.4, 80]

nodes_to_add:
 #- "AAAXX" where AAA is a 3-letter country code, 
 # specified in the "geographic scope" 
 # and XX is a 2-letter sub-regional node code. 
 # E.g. - "IDNSM" for a sub-regional node in Sumatra, Indonesia.

nodes_to_remove:
#- "AAAXX" where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code

powerplant_build_rates:
 # [TECHNOLOGY, COUNTRY, METHOD, VALUE, START_YEAR, END_YEAR]
 # where TECHNOLOGY_TYPE is, for example, all coal powerplants and is in the 
 # format COA.
 # COUNTRY is the 3-letter country code. E.g. "IND" for "Indonesia" 
 # METHOD specifies how the build rate is applied: absolute ("ABS" or as a 
 # percentage ("PCT") of the maximum capacity for a TECHNOLOGY_TYPE.
 # VALUE is the value - either absolute or percentage - by which the capacity 
 # of the associated TECHNOLOGY can increase. It is applied from the START_YEAR 
 # to the END_YEAR.
 # E.g. - ["SPV", "IND", "ABS", 0, 2020, 2025] 
  - ["SPV", "IND", "PCT", 25, 2020, 2025] 

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
  RM1: [15, 2030, 2050]

emission_limit:
# - [EMISSION, COUNTRY, YEAR, VALUE]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is  
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated.
 - ["CO2", "IND", 2040, 1]

fuel_limits:
# FUEL: [VALUE, COUNTRY/INTERNATIONAL, YEAR]
# Where FUEL is the fuel on which a limit is being applied (e.g. COA), VALUE is
# the value in Petajoules (PJ), COUNTRY/INTERNATIONAL specific which domestic 
# fuel (e.g. IND) or international fuel ("INT") the limit is being applied to, 
# and YEAR is the year for which the limit is applied. All years between multiple 
# fuel extraction constraints will be interpolated.


calibration:
#  OCG1: [50, "IND", 2021]

re_targets:
# E.g. - ["IND", 2030, 2040, 30]
# where "IND" is the country code; 2030, 2040 are the start and end years
# respectively; and 30 is the target between the start and end years (inclusive)
# in %
 - ["IND", 2030, 2040, 30]
