# Scenario Name 
scenario: 'Indonesia'

# Temporal Parameters 
startYear: 2021
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [0, 6]
  D2: [6, 12]
  D3: [12, 18]
  D4: [18, 24]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]
timeshift: 8 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
    - 'IDN'
crossborderTrade: True

# Emission Parameters 
emission_penalty: 2.1 # M$/MT CO2

# Investment Parameters 
no_invest_technologies: 
  - 'CSP'
  - 'WAV'
  - 'BIO'
  - 'URN'
  - 'WOF'
  - 'OTH'
  - 'WAS'

# Result Parameters 
results_by_country: True

# solver parameters
solver: 'cbc' # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, first_year, 'fixed/open']
  TRNIDNJKIDNJB: [10, 2021, 'open']
  TRNIDNJKIDNBT: [10, 2021, 'open']
  TRNIDNYOIDNJT: [10, 2021, 'open']
  TRNIDNJIIDNBA: [2, 2021, 'open']
  TRNIDNJIIDNJT: [4.2, 2021, 'open']
  TRNIDNJBIDNBT: [10, 2021, 'open']
  TRNIDNJBIDNJT: [4.2, 2021, 'open']
  TRNIDNACIDNSU: [2.5, 2021, 'open']
  TRNIDNSUIDNRI: [0.4, 2021, 'open']
  TRNIDNSBIDNRI: [2.5, 2021, 'open']
  TRNIDNRIIDNJA: [2, 2021, 'open']
  TRNIDNJAIDNSB: [0.544, 2021, 'open']
  TRNIDNSSIDNBE: [0.5, 2021, 'open']
  TRNIDNSSIDNLA: [1.5, 2021, 'open']
  TRNIDNBTIDNSS: [3, 2021, 'fixed']
  TRNIDNKBIDNKT: [0.1, 2021, 'open']
  TRNIDNKTIDNKS: [0.1, 2021, 'open']
  TRNIDNKSIDNKI: [0.1, 2021, 'open']
  TRNIDNKIIDNKU: [0.1, 2021, 'open']
  TRNIDNSAIDNGO: [0.1, 2021, 'open']
  TRNIDNGOIDNST: [0.1, 2021, 'open']
  TRNIDNSTIDNSR: [0.1, 2021, 'open']
  TRNIDNSRIDNSN: [0.1, 2021, 'open']

  TRNIDNNBIDNNT: [0.1, 2030, 'open']
  TRNIDNBAIDNNB: [0.1, 2030, 'open']
  TRNIDNSNIDNNB: [0.1, 2030, 'open']
  TRNIDNMAIDNSG: [0.1, 2030, 'open']
  TRNIDNKSIDNSN: [0.1, 2030, 'open']
  TRNIDNKSIDNJI: [0.1, 2030, 'open']
  TRNIDNBAIDNJI: [0.1, 2030, 'open']

nodes_to_add:
 #- 'AAAXX' where AAA is a 3-letter country code, 
 # specified in the 'geographic scope' 
 # and XX is a 2-letter sub-regional node code. 
 # E.g. - 'IDNSM' for a sub-regional node in Sumatra, Indonesia.
 # - 'IDNSM'
 - 'IDNSA'
 - 'IDNMA'
 - 'IDNJK' 
 - 'IDNBT' 
 - 'IDNJB'
 - 'IDNJI'
 - 'IDNRI'
 - 'IDNMU'
 - 'IDNSU'
 - 'IDNLA'
 - 'IDNKB'
 - 'IDNKS'
 - 'IDNKI'
 - 'IDNJT'
 - 'IDNSN'
 - 'IDNAC'
 - 'IDNSS'
 - 'IDNKT'
 - 'IDNKU'
 - 'IDNYO'
 - 'IDNST'
 - 'IDNJA'
 - 'IDNNB'
 - 'IDNBA'
 - 'IDNSB'
 - 'IDNSG' 
 - 'IDNNT'
 - 'IDNBB'
 - 'IDNPB'
 - 'IDNPA'
 - 'IDNGO'
 - 'IDNKR'
 - 'IDNBE'
 - 'IDNSR'

nodes_to_remove:
#- 'AAAXX' where AAA is a 3-letter country code, and XX is a 2-letter sub-national
# code
 - 'IDNXX'

powerplant_build_rates:
 # TECHNOLOGY_TYPE: [METHOD, VALUE, START_YEAR, END_YEAR, METHOD]
 # where TECHNOLOGY_TYPE is, for example, all coal powerplants and is in the 
 # format COA.
 # METHOD specifies how the build rate is applied: absolute ('ABS' or as a 
 # percentage ('PCT') of the maximum capacity for a TECHNOLOGY_TYPE.
 # VALUE is the value - either absolute or percentage - by which the capacity 
 # of the associated TECHNOLOGY can increase. It is applied from the START_YEAR 
 # to the END_YEAR.
 SPV1: ['ABS', 0, 2020, 2025]
 SPV2: ['PCT', 0.25, 2025, 2035]
 SPV3: ['PCT', 1, 2035, 2051]
 WON1: ['ABS', 0, 2020, 2024]
 WON2: ['PCT', 5, 2024, 2051]
 COA1: ['ABS', 0, 2020, 2024]
 CCG1: ['ABS', 0, 2020, 2024]
 GEO1: ['ABS', 0, 2020, 2024]
 GEO2: ['PCT', 5, 2024, 2051]
 BAT1: ['ABS', 0, 2020, 2025]
 BAT2: ['ABS', 0.25, 2025, 2035]
 BAT3: ['ABS', 1, 2035, 2051]

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
 RM1: [60, 2020, 2029]
 RM2: [35, 2030, 2050]
