# Scenario Name 
scenario: "India"

# Temporal Parameters 
startYear: 2021
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [1, 7]
  D2: [7, 13]
  D3: [13, 19]
  D4: [19, 25]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]

timeshift: 0 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
  - "IND"

crossborderTrade: True

# Emission Parameters 
emission_penalty: 
# - [EMISSION, COUNTRY, START_YEAR, END_YEAR, VALUE]
# where VALUE is in M$/MT CO2
 - ["CO2", "IND", 2020, 2050, 2.1]

# Investment Parameters 
no_invest_technologies: 
  - "CSP"
  - "WAV"
  - "URN"
  - "OTH"
  - "WAS"
  - "COG" 
  - "GEO"
  - "BIO"
  - "PET"
  - "LDS"

# Result Parameters 
results_by_country: True

# solver parameters
solver: "cbc" # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, 
  #              build_year, 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              capex_cost, 
  #              efficiency]
  PWRCOAINDWE01: [8, 2000, 2025, 5, 1100, 35]
  PWRBIOINDWE01: [0, 2020, 2030, 2, 2000, 28]
  # Units are in GW (capacity/build_rate_per_year), m$/GW (capex_cost), 
  # % (efficiency).

user_defined_capacity_transmission:
  # entry: [technology,
  #         capacity, 
  #         build_year, 
  #         first_year_of_expansion, 
  #         build_rate_per_year, 
  #         capex_cost,
  #         annual_fixed_O&M_cost,
  #         variable_O&M_cost,
  #         efficiency]
  trn1: [TRNINDEAINDNE, 5, 1975, 2030, 10, 350, 13, 4, 95]
  trn2: [TRNINDEAINDNE, 1, 1990, 2030, 10, 350, 13, 4, 95]
  trn3: [TRNINDEAINDNE, 2, 2035, 2030, 10, 350, 13, 4, 95]
  trn4: [TRNINDNOINDSO, 0, 2020, 2025, 0.5, 620, 24, 4, 92]
  # Per technology, only the capacity and build_year
  # parameters can deviate from each other. For all other
  # parameters only the last entry will be used.

user_defined_capacity_storage:
  # entry: [technology, 
  #         capacity, 
  #         build_year, 
  #         first_year_of_expansion, 
  #         build_rate_per_year, 
  #         capex_cost, 
  #         annual_fixed_O&M_cost, 
  #         variable_O&M_cost, 
  #         roundtrip_efficiency]
  sto1: [PWRSDSINDWE01, 2, 2010, 2025, 3, 1800, 40, 0, 87]
  sto2: [PWRLDSINDNE01, 4, 1985, 2025, 2, 3400, 19, 0.5, 82]
  sto3: [PWRLDSINDNE01, 1, 2030, 2025, 2, 3400, 19, 0.5, 82]
  # Per technology, only the capacity and build_year
  # parameters can deviate from each other. For all other
  # parameters only the last entry will be used.
  # Units are in GW (capacity/build_rate_per_year), m$/GW (capex_cost/annual_fixed_O&M_cost), 
  # $/MWh (variable_O&M_cost), % (roundtrip_efficiency).

transmission_parameters:
  # technology_group: [Line CAPEX, 
  #                    Converter pair CAPEX, 
  #                    Line losses, 
  #                    AC/DC Converter pair losses, 
  #                    Fixed O&M costs, 
  #                    Variable O&M costs]
  # Units are in $2020/MW/KM (Line CAPEX), $2020/MW (Converter pair CAPEX),
  # %/1000km (Line losses), % (AC/DC Converter pair losses), 
  # % of total CAPEX/yr (Fixed O&M costs), $/MWh (Variable O&M costs).
  HVAC: [779, 95400, 6.75, 0, 3.5, 4]
  HVDC: [238, 297509, 3.5, 1.3, 3.5, 4]
  HVDC_subsea: [295, 297509, 3.5, 1.3, 3.5, 4]

storage_parameters:
  # technology_group: [capex_cost,
  #                    annual_fixed_O&M_cost,
  #                    variable_O&M_cost,
  #                    roundtrip_efficiency,
  #                    duration]
  # Units are in m$/GW (capex_cost, annual_fixed_O&M_cost), $/MWh (variable_O&M_cost),
  # % (roundtrip_efficiency), hours (duration = storage capacity (GWh)/Power rating (GW)).
  SDS: [1938, 44.25, 0, 85, 4]
  LDS: [3794, 20.2, 0.58, 80, 10]

nodes_to_add:
 #- "AAAXX" where AAA is a 3-letter country code, 
 # specified in the "geographic scope" 
 # and XX is a 2-letter sub-regional node code. 
 # E.g. - "IDNSM" for a sub-regional node in Sumatra, Indonesia.

nodes_to_remove:
#- "AAAXX" where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
  RM1: [10, 2025, 2029]
  RM2: [15, 2030, 2050]
  
reserve_margin_technologies:
# TECHNOLOGY: PERCENTAGE,
# Specify the share of capacity (%) per technology that can contribute to the
# reserve margin. Technologies that are not listed are excluded from contributing.
  BIO : 90
  CCG : 90
  COA : 90
  COG : 50
  CSP : 30
  GEO : 90
  HYD : 30
  OCG : 90
  OIL : 90
  OTH : 90
  PET : 90
  SPV : 0
  URN : 90
  WAS : 90
  WAV : 10
  WOF : 10
  WON : 10
  TRN : 10
  SDS : 69
  LDS : 77

emission_limit:
# - [EMISSION, COUNTRY, TYPE, YEAR, VALUE]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is  
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated if TYPE is set to "LINEAR". If "POINT" is used
# it means that a singular year value is set without interpolation occuring in
# previous target years. A combination of TYPE targets can be set per EMISSION and
# COUNTRY yet only a single target per YEAR.
 - ["CO2", "IND", "POINT", 2048, 0]
 - ["CO2", "IND", "LINEAR", 2040, 1]
 - ["CO2", "IND", "LINEAR", 2028, 400]
 - ["CO2", "IND", "POINT", 2030, 300]

calibration:
# TECHNOLOGY: [VALUE, COUNTRY, YEAR]
# where VALUE is percentage (%) availability of a given technology. This can be used
# to constrain power plant output (generation).
  OCG1: [50, "IND", 2021]

re_targets:
# TARGET: [COUNTRY/NODE, [TECHNOLOGY], START_YEAR, END_YEAR, VALUE]
# E.g. TO1: ["IND", [], "PCT", 2030, 2040, 60]
# E.g. TO2: ["INDSO", ['WOF', 'WON'], "PCT", 2025, 2045, 15]
# E.g. TO3: ["INDSO", ['WOF'], "ABS", 2040, 2050, 200]
# Targets can be set in absolute terms ("ABS", VALUE = GW) or in relative terms 
# ("PCT", VALUE = %) where targets in relative terms represent the share of generation.
# For "PCT", targets can be set at national (e.g. "IND") and nodal levels (e.g. "INDSO")
# whereas "ABS" can only be set at nodal levels. For "PCT", a single technology can 
# be set for the target (e.g. ["WOF"]) a technology subset can be set (e.g. ['WOF', 'WON'])
# or the TECHNOLOGY list can be left empty (e.g. []) as such that all renewable
# technologies contribute to the target. For "ABS", only one technology can be 
# selected per target. Note that a combination of targets can be set that affect
# the same countries/nodes/technologies. This can be computationally intensive.
  T01: ["IND", [], "PCT", 2030, 2040, 60]
  T02: ["INDSO", ['WOF','WON'], "PCT", 2025, 2045, 15]
  T03: ["INDSO", ['WOF'], "ABS", 2040, 2050, 200]  