# Scenario Name 
scenario: "India"

# Temporal Parameters 
startYear: 2021
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [1, 7]
  D2: [7, 13]
  D3: [13, 19]
  D4: [19, 25]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]

timeshift: 0 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
  - "IND"
 # - "MMR"  

crossborderTrade: True

# Emission Parameters 
emission_penalty: 
# - [EMISSION, COUNTRY, START_YEAR, END_YEAR, VALUE]
# where VALUE is in M$/MT CO2
 - ["CO2", "IND", 2020, 2050, 2.1]

# Investment Parameters 
no_invest_technologies: 
  - "CSP"
  - "WAV"
  - "URN"
  - "OTH"
  - "WAS"
  - "COG" 
  - "GEO"
  - "BIO"
  - "PET"
  - "LDS"

# Result Parameters 
results_by_country: True

# solver parameters
solver: "cbc" # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, 
  #              build_year, 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              capex_cost, 
  #              efficiency]
  PWRCOAINDWE01: [8, 2000, 2025, 5, 1100, 35]
  PWRBIOINDWE01: [0, 2020, 2030, 2, 2000, 28]
  # Units are in GW (capacity/build_rate_per_year), m$/GW (capex_cost), 
  # % (efficiency).

user_defined_capacity_transmission:
  # entry: [technology,
  #         capacity, 
  #         build_year, 
  #         first_year_of_expansion, 
  #         build_rate_per_year, 
  #         capex_cost,
  #         annual_fixed_O&M_cost,
  #         variable_O&M_cost,
  #         efficiency]
  trn1: [TRNINDEAINDNE, 5, 1975, 2030, 10, 350, 13, 4, 95]
  trn2: [TRNINDEAINDNE, 1, 1990, 2030, 10, 350, 13, 4, 95]
  trn3: [TRNINDEAINDNE, 2, 2035, 2030, 10, 350, 13, 4, 95]
  trn4: [TRNINDNOINDSO, 0, 2020, 2025, 0.5, 620, 24, 4, 92]
  # Per technology, only the capacity and build_year
  # parameters can deviate from each other. For all other
  # parameters only the last entry will be used.

user_defined_capacity_storage:
  # entry: [technology, 
  #         capacity, 
  #         build_year, 
  #         first_year_of_expansion, 
  #         build_rate_per_year, 
  #         capex_cost, 
  #         annual_fixed_O&M_cost, 
  #         variable_O&M_cost, 
  #         roundtrip_efficiency]
  sto1: [PWRSDSINDWE01, 2, 2010, 2025, 3, 1800, 40, 0, 87]
  sto2: [PWRLDSINDNE01, 4, 1985, 2025, 2, 3400, 19, 0.5, 82]
  sto3: [PWRLDSINDNE01, 1, 2030, 2025, 2, 3400, 19, 0.5, 82]
  # Per technology, only the capacity and build_year
  # parameters can deviate from each other. For all other
  # parameters only the last entry will be used.
  # Units are in GW (capacity/build_rate_per_year), m$/GW (capex_cost/annual_fixed_O&M_cost), 
  # $/MWh (variable_O&M_cost), % (roundtrip_efficiency).

transmission_parameters:
  # technology_group: [Line CAPEX, 
  #                    Converter pair CAPEX, 
  #                    Line losses, 
  #                    AC/DC Converter pair losses, 
  #                    Fixed O&M costs, 
  #                    Variable O&M costs]
  # Units are in $2020/MW/KM (Line CAPEX), $2020/MW (Converter pair CAPEX),
  # %/1000km (Line losses), % (AC/DC Converter pair losses), 
  # % of total CAPEX/yr (Fixed O&M costs), $/MWh (Variable O&M costs).
  HVAC: [779, 95400, 6.75, 0, 3.5, 4]
  HVDC: [238, 297509, 3.5, 1.3, 3.5, 4]
  HVDC_subsea: [295, 297509, 3.5, 1.3, 3.5, 4]

storage_parameters:
  # technology_group: [capex_cost,
  #                    annual_fixed_O&M_cost,
  #                    variable_O&M_cost,
  #                    roundtrip_efficiency,
  #                    duration]
  # Units are in m$/GW (capex_cost, annual_fixed_O&M_cost), $/MWh (variable_O&M_cost),
  # % (roundtrip_efficiency), hours (duration = storage capacity (GWh)/Power rating (GW)).
  SDS: [1938, 44.25, 0, 85, 4]
  LDS: [3794, 20.2, 0.58, 80, 10]

nodes_to_add:
 #- "AAAXX" where AAA is a 3-letter country code, 
 # specified in the "geographic scope" 
 # and XX is a 2-letter sub-regional node code. 
 # E.g. - "IDNSM" for a sub-regional node in Sumatra, Indonesia.

nodes_to_remove:
#- "AAAXX" where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code

powerplant_build_rates:
 # [TECHNOLOGY, COUNTRY, METHOD, VALUE, START_YEAR, END_YEAR]
 # where TECHNOLOGY_TYPE is, for example, all coal powerplants and is in the 
 # format COA.
 # COUNTRY is the 3-letter country code. E.g. "IND" for "Indonesia" 
 # METHOD specifies how the build rate is applied: absolute ("ABS" or as a 
 # percentage ("PCT") of the maximum capacity for a TECHNOLOGY_TYPE.
 # VALUE is the value - either absolute or percentage - by which the capacity 
 # of the associated TECHNOLOGY can increase. It is applied from the START_YEAR 
 # to the END_YEAR.
 # E.g. - ["SPV", "IND", "ABS", 0, 2020, 2025] 
  - ["SPV", "IND", "PCT", 25, 2020, 2025] 

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
  RM1: [10, 2025, 2029]
  RM2: [15, 2030, 2050]
  
reserve_margin_technologies:
# TECHNOLOGY: PERCENTAGE,
# Specify the share of capacity (%) per technology that can contribute to the
# reserve margin. Technologies that are not listed are excluded from contributing.
  BIO : 90
  CCG : 90
  COA : 90
  COG : 50
  CSP : 30
  GEO : 90
  HYD : 30
  OCG : 90
  OIL : 90
  OTH : 90
  PET : 90
  SPV : 0
  URN : 90
  WAS : 90
  WAV : 10
  WOF : 10
  WON : 10
  TRN : 10
  SDS : 69
  LDS : 77

emission_limit:
# - [EMISSION, COUNTRY, YEAR, VALUE]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is  
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated.
 - ["CO2", "IND", 2040, 1]

fuel_limits:
# FUEL: [VALUE, COUNTRY/INTERNATIONAL, YEAR]
# Where FUEL is the fuel on which a limit is being applied (e.g. COA), VALUE is
# the value in Petajoules (PJ), COUNTRY/INTERNATIONAL specific which domestic 
# fuel (e.g. IND) or international fuel ("INT") the limit is being applied to, 
# and YEAR is the year for which the limit is applied. All years between multiple 
# fuel extraction constraints will be interpolated.


calibration:
#  OCG1: [50, "IND", 2021]

re_targets:
# E.g. - ["IND", 2030, 2040, 30]
# where "IND" is the country code; 2030, 2040 are the start and end years
# respectively; and 30 is the target between the start and end years (inclusive)
# in %
  T01: ["IND", [], "PCT", 2030, 2040, 60]
  T02: ["IND", ['WOF'], "PCT", 2025, 2045, 10]
  T03: ["IND", ['SPV'], "ABS", 2025, 2045, 30]  
  #T04: ["MMR", [], "PCT", 2041, 2050, 80]