# Scenario Name 
scenario: 'APG24_v1_LC'

# Temporal Parameters 
startYear: 2021
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [1, 5]
  D2: [5, 9]
  D3: [9, 13]
  D4: [13, 17]
  D5: [17, 21]
  D6: [21, 25]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]

timeshift: 8 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
    - 'IDN'
    - 'VNM'
    - 'MYS'
    - 'PHL'
    - 'THA'
    - 'LAO'
    - 'MMR'
    - 'SGP'
    - 'KHM'
    - 'BRN'
    # - 'ZAF'
    # - 'AGO'
    # - 'BDI'
    # - 'BEN'
    # - 'BFA'
    # - 'BWA'
    # - 'CAF'
    # - 'CIV'
    # - 'CMR'
    # - 'COD'
    # - 'COG'
    # - 'CPV'
    # - 'DJI'
    # - 'DZA'
    # - 'EGY'
    # - 'ERI'
    # - 'ESH'
    # - 'ETH'
    # - 'GAB'
    # - 'GHA'
    # - 'GIN'
    # - 'GMB'
    # - 'GNB'
    # - 'GNQ'
    # - 'KEN'
    # - 'LBR'
    # - 'LBY'
    # - 'LSO'
    # - 'MAR'
    # - 'MDG'
    # - 'MLI'
    # - 'MOZ'
    # - 'MRT'
    # - 'MUS'
    # - 'MWI'
    # - 'NAM'
    # - 'NER'
    # - 'NGA'
    # - 'RWA'
    # - 'SDN'
    # - 'SEN'
    # - 'SLE'
    # - 'SOM'
    # - 'SWZ'
    # - 'TCD'
    # - 'TGO'
    # - 'TUN'
    # - 'TZA'
    # - 'UGA'
    # - 'ZMB'
    # - 'ZWE'

crossborderTrade: True

# Emission Parameters 
emission_penalty: 
# - [EMISSION, COUNTRY, START_YEAR, END_YEAR, VALUE]
# where VALUE is in M$/MT CO2
 - ['CO2', 'IDN', 2020, 2050, 2.1]

# Investment Parameters 
no_invest_technologies: 
  - 'CSP'
  - 'WAV'
#  - 'URN'
#  - 'WOF'
  - 'OTH'
#  - 'WAS'
#  - 'COA'
  - 'COG' 
#  - 'GEO'
#  - 'CCS'
#  - 'BIO'
  - 'PET'
#  - 'OIL'

# Result Parameters 
results_by_country: True

# solver parameters
solver: 'gurobi' # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, 
  #              first_year, 
  #              'fixed/open', 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              cost]
  # Indonesia
  TRNIDNJWIDNNU: [2, 2020, 'open', 2030, 1, 300]
  TRNIDNJWIDNSM: [3, 2024, 'open', 2030, 1, 300]

  TRNIDNSLIDNNU: [0.001, 2030, 'open', 2030, 1, 1350]
  TRNIDNMLIDNSL: [0.001, 2030, 'open', 2030, 1, 1350]
  TRNIDNKAIDNSL: [0.001, 2030, 'open', 2030, 1, 1350]
  TRNIDNKAIDNJW: [0.001, 2030, 'open', 2030, 1, 1350]
  TRNIDNMLIDNPP: [0.001, 2030, 'open', 2030, 1, 1350]

  # APG intra-country
  TRNTHACETHASO: [0.001, 2020, 'open', 2030, 1, 300]
  TRNTHANOTHACE: [0.001, 2020, 'open', 2030, 1, 300]
  TRNPHLLUPHLVI: [0.4, 2020, 'open', 2030, 1, 300]
  TRNPHLVIPHLMI: [0.001, 2030, 'open', 2030, 1, 300]
  TRNVNMCEVNMSO: [12, 2020, 'open', 2030, 1, 300]
  TRNVNMNOVNMCE: [2.2, 2020, 'open', 2030, 1, 300]

  # APG inter-country
    # Existing
  TRNKHMXXLAOXX: [0.2, 2020, 'open', 2030, 1, 300]
  TRNKHMXXTHACE: [0.23, 2020, 'open', 2030, 1, 300]
  TRNKHMXXVNMSO: [0.2, 2020, 'open', 2030, 1, 300]
  TRNLAOXXVNMNO: [0.538, 2020, 'open', 2030, 1, 300]
  TRNLAOXXTHANO: [5.427, 2020, 'open', 2030, 1, 300]
  TRNTHASOMYSPE: [0.3, 2020, 'open', 2030, 1, 300]
  TRNMYSSKIDNKA: [0.23, 2020, 'open', 2030, 1, 300]
  TRNMYSPESGPXX: [0.525, 2020, 'open', 2030, 1, 300]

    # New 
  TRNBRNXXMYSSK: [0.001, 2030, 'open', 2030, 1, 300]
  TRNLAOXXMMRXX: [0.001, 2030, 'open', 2030, 1, 300]
  TRNMMRXXTHANO: [0.369, 2030, 'open', 2030, 1, 300]
  TRNMYSPEMYSSK: [0.001, 2030, 'open', 2030, 1, 1350]
  TRNMYSSHIDNKA: [0.001, 2030, 'open', 2030, 1, 300]
  TRNMYSPEIDNSM: [0.5, 2030, 'open', 2030, 1, 300]
  TRNMYSSKMYSSH: [0.001, 2030, 'open', 2030, 1, 300]
  TRNMYSSHPHLLU: [0.5, 2030, 'open', 2030, 1, 1350]
  TRNSGPXXIDNSM: [0.6, 2030, 'open', 2030, 1, 300]

nodes_to_add:
 #- 'AAAXX' where AAA is a 3-letter country code, 
 # specified in the 'geographic scope' 
 # and XX is a 2-letter sub-regional node code. 
 # E.g. - 'IDNSM' for a sub-regional node in Sumatra, Indonesia.
 # - 'IDNSM'
  - 'IDNJW'
  - 'IDNKA'
  - 'IDNSM'
  - 'IDNNU'
  - 'IDNSL'
  - 'IDNML'
  - 'IDNPP'
  - 'VNMNO'
  - 'VNMCE'
  - 'VNMSO'
  - 'MYSPE'
  - 'MYSSH'
  - 'MYSSK'
  - 'PHLLU'
  - 'PHLVI'
  - 'PHLMI'
  - 'THANO'
  - 'THACE'
  - 'THASO'
  - 'LAOXX'
  - 'KHMXX'
  - 'SGPXX'
  - 'BRNXX'
  - 'MMRXX'

nodes_to_remove:
#- 'AAAXX' where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code
 - 'IDNXX'
 - 'VNMXX'
 - 'MYSXX'
 - 'PHLXX'
 - 'THAXX'

powerplant_build_rates:
 # TECHNOLOGY_TYPE: [COUNTRY, METHOD, VALUE, START_YEAR, END_YEAR, METHOD]
 # where TECHNOLOGY_TYPE is, for example, all coal powerplants and is in the 
 # format COA.
 # COUNTRY is the 3-letter country code. E.g. 'IDN' for 'Indonesia' 
 # METHOD specifies how the build rate is applied: absolute ('ABS' or as a 
 # percentage ('PCT') of the maximum capacity for a TECHNOLOGY_TYPE.
 # VALUE is the value - either absolute or percentage - by which the capacity 
 # of the associated TECHNOLOGY can increase. It is applied from the START_YEAR 
 # to the END_YEAR.
 # E.g. - ['SPV', 'IDN', 'ABS', 0, 2020, 2025] 


reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
 RM1: [15, 2020, 2029]
 RM2: [15, 2030, 2050]

emission_limit:
# - [EMISSION, COUNTRY, YEAR, VALUE]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is  
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated.
 - ['CO2', 'IDN', 2030, 99999]
#  - ['CO2', 'BRN', 2030, 5]
#  - ['CO2', 'KHM', 2030, 20]
#  - ['CO2', 'IDN', 2030, 316]
#  - ['CO2', 'LAO', 2030, 5]
#  - ['CO2', 'MYS', 2030, 106]
#  - ['CO2', 'MMR', 2030, 7]
#  - ['CO2', 'PHL', 2030, 130]
#  - ['CO2', 'SGP', 2030, 39]
#  - ['CO2', 'THA', 2030, 192]
#  - ['CO2', 'VNM', 2030, 283]
#  - ['CO2', 'BRN', 2050, 1.7]
#  - ['CO2', 'KHM', 2050, 6.7]
#  - ['CO2', 'IDN', 2050, 105.3]
#  - ['CO2', 'LAO', 2050, 1.7]
#  - ['CO2', 'MYS', 2050, 35.3]
#  - ['CO2', 'MMR', 2050, 2.3]
#  - ['CO2', 'PHL', 2050, 43.3]
#  - ['CO2', 'SGP', 2050, 13]
#  - ['CO2', 'THA', 2050, 64]
#  - ['CO2', 'VNM', 2050, 94.3]


fuel_limits:
# FUEL: [VALUE, COUNTRY/INTERNATIONAL, YEAR]
# Where FUEL is the fuel on which a limit is being applied (e.g. COA), VALUE is
# the value in Petajoules (PJ), COUNTRY/INTERNATIONAL specific which domestic 
# fuel (e.g. IDN) or international fuel ('INT') the limit is being applied to, 
# and YEAR is the year for which the limit is applied. All years between multiple 
# fuel extraction constraints will be interpolated.
#  - ['GAS', 'IDN', 453, 2021]
#  - ['GAS', 'IDN', 933, 2035]
#  - ['GAS', 'IDN', 933, 2050]
#  - ['COA', 'IDN', 3300, 2021]
#  - ['COA', 'IDN', 3300, 2050]
#  - ['OIL', 'IDN', 0, 2021]
#  - ['OIL', 'IDN', 0, 2050]

#  - ['GAS', 'VNM', 89, 2021]
#  - ['GAS', 'VNM', 178, 2035]
#  - ['GAS', 'VNM', 178, 2050]
#  - ['COA', 'VNM', 510, 2021]
#  - ['COA', 'VNM', 510, 2050]
#  - ['OIL', 'VNM', 0, 2021]
#  - ['OIL', 'VNM', 0, 2050]

#  - ['GAS', 'MYS', 667, 2021]
#  - ['GAS', 'MYS', 1335, 2035]
#  - ['GAS', 'MYS', 1335, 2050]
#  - ['COA', 'MYS', 0, 2021]
#  - ['COA', 'MYS', 0, 2050]
#  - ['OIL', 'MYS', 0, 2021]
#  - ['OIL', 'MYS', 0, 2050]

#  - ['GAS', 'PHL', 35, 2021]
#  - ['GAS', 'PHL', 71, 2035]
#  - ['GAS', 'PHL', 71, 2050]
#  - ['COA', 'PHL', 129, 2021]
#  - ['COA', 'PHL', 129, 2050]
#  - ['OIL', 'PHL', 0, 2021]
#  - ['OIL', 'PHL', 0, 2050]

#  - ['GAS', 'LAO', 0, 2021]
#  - ['GAS', 'LAO', 0, 2035]
#  - ['GAS', 'LAO', 0, 2050]
#  - ['COA', 'LAO', 236, 2021]
#  - ['COA', 'LAO', 236, 2050]
#  - ['OIL', 'LAO', 0, 2021]
#  - ['OIL', 'LAO', 0, 2050]

#  - ['GAS', 'THA', 339, 2021]
#  - ['GAS', 'THA', 678, 2035]
#  - ['GAS', 'THA', 678, 2050]
#  - ['COA', 'THA', 140, 2021]
#  - ['COA', 'THA', 140, 2050]
#  - ['OIL', 'THA', 0, 2021]
#  - ['OIL', 'THA', 0, 2050]

#  - ['GAS', 'KHM', 0, 2021]
#  - ['GAS', 'KHM', 0, 2035]
#  - ['GAS', 'KHM', 0, 2050]
#  - ['COA', 'KHM', 0, 2021]
#  - ['COA', 'KHM', 0, 2050]
#  - ['OIL', 'KHM', 0, 2021]
#  - ['OIL', 'KHM', 0, 2050]

#  - ['GAS', 'SGP', 0, 2021]
#  - ['GAS', 'SGP', 0, 2035]
#  - ['GAS', 'SGP', 0, 2050]
#  - ['COA', 'SGP', 0, 2021]
#  - ['COA', 'SGP', 0, 2050]
#  - ['OIL', 'SGP', 0, 2021]
#  - ['OIL', 'SGP', 0, 2050]

#  - ['GAS', 'BRN', 108, 2021]
#  - ['GAS', 'BRN', 216, 2035]
#  - ['GAS', 'BRN', 216, 2050]
#  - ['COA', 'BRN', 0, 2021]
#  - ['COA', 'BRN', 0, 2050]
#  - ['OIL', 'BRN', 0, 2021]
#  - ['OIL', 'BRN', 0, 2050]

#  - ['GAS', 'MMR', 157, 2021]
#  - ['GAS', 'MMR', 315, 2035]
#  - ['GAS', 'MMR', 315, 2050]
#  - ['COA', 'MMR', 0, 2021]
#  - ['COA', 'MMR', 0, 2050]
#  - ['OIL', 'MMR', 0, 2021]
#  - ['OIL', 'MMR', 0, 2050]

calibration:
 OCG1: [50, 'IDN', 2021]
 OCG2: [60, 'IDN', 2022]
 OCG3: [49, 'IDN', 2023]
 OCG4: [49, 'IDN', 2024]
 OCG5: [49, 'IDN', 2025]
 OCG6: [48, 'IDN', 2026]
 OCG7: [46, 'IDN', 2027]
 OCG8: [42, 'IDN', 2028]
 OCG9: [41, 'IDN', 2029]
 OCG10: [41, 'IDN', 2030]
 CCG1: [70, 'IDN', 2021]
 CCG2: [70, 'IDN', 2022]
 CCG3: [59, 'IDN', 2023]
 CCG4: [51, 'IDN', 2024]
 CCG5: [50, 'IDN', 2025]
 CCG6: [45, 'IDN', 2026]
 CCG7: [40, 'IDN', 2027]
 CCG8: [36, 'IDN', 2028]
 CCG9: [36, 'IDN', 2029]
 CCG10: [35, 'IDN', 2030]


re_targets:
# E.g. - ['IDN', 2030, 2040, 30]
# where 'IDN' is the country code; 2030, 2040 are the start and end years
# respectively; and 30 is the target between the start and end years (inclusive)
# in %
# - ['BRN', 2035, 2050, 30]
 - ['KHM', 2030, 2050, 25]
 - ['IDN', 2030, 2050, 20]
 - ['LAO', 2025, 2050, 20]
 - ['MYS', 2025, 2034, 31]
 - ['MYS', 2035, 2050, 40]
 - ['MMR', 2030, 2050, 39]
 - ['PHL', 2030, 2039, 35]
 - ['PHL', 2040, 2050, 50]
 - ['THA', 2037, 2050, 20]
 - ['VNM', 2030, 2049, 32]
 - ['VNM', 2050, 2050, 43]
