# Scenario Name 
scenario: 'Vietnam_LC'

# Temporal Parameters 
startYear: 2021
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [0, 6]
  D2: [6, 12]
  D3: [12, 18]
  D4: [18, 24]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]
timeshift: 8 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
    - 'VNM'
crossborderTrade: True

# Emission Parameters 
emission_penalty: 0 # M$/MT CO2

# Investment Parameters 
no_invest_technologies: 
  - 'CSP'
  - 'WAV'
  - 'URN'
  - 'WOF'
  - 'OTH'
  - 'WAS'

# Result Parameters 
results_by_country: True

# solver parameters
solver: 'cbc' # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, first_year, 'fixed/open']

nodes_to_add:
 #- 'AAAXX' where AAA is a 3-letter country code, 
 # specified in the 'geographic scope' 
 # and XX is a 2-letter sub-regional node code. 
 # E.g. - 'IDNSM' for a sub-regional node in Sumatra, Indonesia.
 # - 'IDNSM'


nodes_to_remove:
#- 'AAAXX' where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code
# - 'IDNXX'

powerplant_build_rates:
 # TECHNOLOGY_TYPE: [METHOD, VALUE, START_YEAR, END_YEAR, METHOD]
 # where TECHNOLOGY_TYPE is, for example, all coal powerplants and is in the 
 # format COA.
 # METHOD specifies how the build rate is applied: absolute ('ABS' or as a 
 # percentage ('PCT') of the maximum capacity for a TECHNOLOGY_TYPE.
 # VALUE is the value - either absolute or percentage - by which the capacity 
 # of the associated TECHNOLOGY can increase. It is applied from the START_YEAR 
 # to the END_YEAR.
 SPV1: ['ABS', 0, 2020, 2025]
 SPV2: ['PCT', 5, 2025, 2035]
 SPV3: ['PCT', 10, 2035, 2051]
 WON1: ['ABS', 0, 2020, 2025]
 WON2: ['PCT', 5, 2025, 2051]
 COA1: ['ABS', 0, 2020, 2024]
 CCG1: ['ABS', 0, 2020, 2024]
 GEO1: ['ABS', 0, 2020, 2024]
 GEO2: ['PCT', 5, 2024, 2051]
 BAT1: ['ABS', 0, 2020, 2025]
 BAT2: ['ABS', 5, 2025, 2051]
 BIO1: ['ABS', 0, 2020, 2025]
 BIO2: ['PCT', 5, 2025, 2051]
 URN1: ['ABS', 0, 2020, 2039]
 URN2: ['ABS', 0, 2039, 2051]
 HYD1: ['ABS', 0, 2020, 2025]
 HYD2: ['PCT', 5, 2025, 2051]

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
 RM1: [60, 2020, 2029]
 RM2: [35, 2030, 2039]
 RM3: [15, 2040, 2050]

emission_limit:
# EMISSION_LIMIT: [VALUE, YEAR]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is the 
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated.
 EL1: [2040, 9999]
 EL2: [2050, 9999]
